name: Check Mime types

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * Sun'  # every sunday at midnight


jobs:
  build:

    runs-on: mattpolzin2/idris-docker:latest

    steps:
    - uses: actions/checkout@v3

    - name: checkDiff
      run: ./generator/checkDiff.sh
